name: Trigger auto deployment for cryovizweb-py

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cryovizweb-py-AutoDeployTrigger-b4edd31a-9d25-4059-bb0e-399dcf13bd8e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CRYOVIZWEBPY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CRYOVIZWEBPY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CRYOVIZWEBPY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/dockerfile
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: cryovizregistry.azurecr.io
          registryUsername: ${{ secrets.CRYOVIZWEBPY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CRYOVIZWEBPY_REGISTRY_PASSWORD }}
          containerAppName: cryovizweb-py
          resourceGroup: WebViewer
          imageToBuild: cryovizregistry.azurecr.io/cryovizweb-py:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


